from fastapi import APIRouter, Depends, HTTPException, Request

from app.security.api_key_auth import verify_copilot_api_key
from app.services.audit_log_service import save_audit_event
from app.services.orchestrator_service import orchestrate_user_query


router = APIRouter(
    prefix="/copilot",
    tags=["Copilot Orchestrator"],
)


@router.get("/ask")
def ask_copilot(
    request: Request,
    query: str,
    top_k: int = 8,
    conversation_id: str | None = None,
    authorized: bool = Depends(verify_copilot_api_key),
):
    """
    Main copilot endpoint.

    What this endpoint does:
    1. Accepts a natural language user question.
    2. Optionally accepts a conversation_id for persistent memory.
    3. Reads request_id from middleware.
    4. Sends the query to the orchestrator service.
    5. Saves audit events for both successful and failed requests.
    6. Returns the routed response.
    """

    # Read request_id generated by middleware.
    request_id = getattr(request.state, "request_id", None)

    try:
        # Keep top_k controlled so we do not send too much context to the LLM.
        if top_k < 1 or top_k > 10:
            error_message = "top_k must be between 1 and 10."

            # Save failed audit event before returning the validation error.
            save_audit_event(
                event_type="copilot_request",
                conversation_id=conversation_id,
                user_query=query,
                route="validation_error",
                record_id=None,
                business_domain=None,
                confidence_score=None,
                confidence_label=None,
                human_review_required=True,
                memory_used=False,
                memory_saved=False,
                status="failed",
                error_message=error_message,
                request_id=request_id,
            )

            raise HTTPException(
                status_code=400,
                detail=error_message,
            )

        # Route the user query to the correct backend flow.
        # request_id is passed so audit logs can store the same trace ID.
        response = orchestrate_user_query(
            query=query,
            top_k=top_k,
            conversation_id=conversation_id,
            request_id=request_id,
        )

        return response

    except HTTPException:
        raise

    except Exception as exc:
        error_message = f"Failed to process copilot query: {str(exc)}"

        # Save failed audit event for unexpected backend errors.
        save_audit_event(
            event_type="copilot_request",
            conversation_id=conversation_id,
            user_query=query,
            route="system_error",
            record_id=None,
            business_domain=None,
            confidence_score=None,
            confidence_label=None,
            human_review_required=True,
            memory_used=False,
            memory_saved=False,
            status="failed",
            error_message=error_message,
            request_id=request_id,
        )

        raise HTTPException(
            status_code=500,
            detail=error_message,
        )