from fastapi import APIRouter, Depends, HTTPException, Request

from app.security.api_key_auth import verify_copilot_api_key
from app.services.audit_log_service import save_audit_event
from app.services.orchestrator_service import orchestrate_user_query


router = APIRouter(
    prefix="/copilot",
    tags=["Copilot Orchestrator"],
)


@router.get("/ask")
async def ask_copilot(
    request: Request,
    query: str,
    top_k: int = 8,
    conversation_id: str | None = None,
    authorized: bool = Depends(verify_copilot_api_key),
):
    """
    Main copilot endpoint.

    This endpoint now calls the orchestrator using MCP.

    Flow:
    Frontend
        -> FastAPI /copilot/ask
        -> orchestrator_service
        -> MCP client service
        -> MCP server tools
        -> backend SQL/RAG/memory APIs
    """

    # Read request_id generated by middleware.
    request_id = getattr(request.state, "request_id", None)

    try:
        # Keep top_k controlled so we do not send too much context to the LLM.
        if top_k < 1 or top_k > 10:
            error_message = "top_k must be between 1 and 10."

            save_audit_event(
                event_type="copilot_request",
                conversation_id=conversation_id,
                user_query=query,
                route="validation_error",
                record_id=None,
                business_domain=None,
                confidence_score=None,
                confidence_label=None,
                human_review_required=True,
                memory_used=False,
                memory_saved=False,
                status="failed",
                error_message=error_message,
                request_id=request_id,
            )

            raise HTTPException(
                status_code=400,
                detail=error_message,
            )

        # Route the user query to the MCP-powered orchestrator.
        result = await orchestrate_user_query(
            query=query,
            top_k=top_k,
            conversation_id=conversation_id,
            request_id=request_id,
        )

        return result

    except HTTPException:
        raise

    except Exception as exc:
        error_message = f"Failed to process copilot query: {str(exc)}"

        save_audit_event(
            event_type="copilot_request",
            conversation_id=conversation_id,
            user_query=query,
            route="system_error",
            record_id=None,
            business_domain=None,
            confidence_score=None,
            confidence_label=None,
            human_review_required=True,
            memory_used=False,
            memory_saved=False,
            status="failed",
            error_message=error_message,
            request_id=request_id,
        )

        raise HTTPException(
            status_code=500,
            detail=error_message,
        )